In [1]:
from cvxpy import *
import numpy as np

m, n = (30, 20)
np.random.seed(1)

A = np.asmatrix(np.random.randn(m, n))
b = np.asmatrix(np.random.randn(m, 1))

In [2]:
x = Variable(n)

cost = sum_squares(A * x - b)

objective = Minimize(cost)
constraints = [0 <= x, x <= 1]
prob = Problem(objective, constraints)

result = prob.solve()

In [3]:
print('Optimal x:\n', x.value)
print('Optimal lagrange multiplier:\n', 
      constraints[0].dual_value, 
      constraints[1].dual_value)

Optimal x:
 [[  2.74656694e-08]
 [  2.85638784e-02]
 [  2.75730621e-08]
 [  4.78327626e-08]
 [  2.63777287e-09]
 [  1.49296787e-01]
 [  1.19199028e-07]
 [  2.09648396e-08]
 [  2.46747598e-01]
 [  5.78236593e-01]
 [  5.29023642e-09]
 [  1.01716277e-03]
 [  8.73750280e-09]
 [  2.26771054e-01]
 [  1.37218553e-08]
 [  2.10140304e-08]
 [  4.08413440e-08]
 [  4.52415813e-09]
 [  2.55078041e-08]
 [  6.32814150e-09]]
Optimal lagrange multiplier:
 [[  2.50930786e+00]
 [  2.67848029e-06]
 [  2.78353157e+00]
 [  1.79423617e+00]
 [  1.30858969e+01]
 [  5.59976489e-07]
 [  7.37035767e-01]
 [  3.35348867e+00]
 [  3.53782570e-07]
 [  1.58362470e-07]
 [  8.93824713e+00]
 [  3.08624097e-04]
 [  7.02959474e+00]
 [  3.97069600e-07]
 [  4.71054026e+00]
 [  3.18864112e+00]
 [  2.06076796e+00]
 [  1.00817336e+01]
 [  3.04814645e+00]
 [  8.53266394e+00]] [[  9.19428102e-08]
 [  9.59487136e-08]
 [  9.17209644e-08]
 [  9.18639022e-08]
 [  9.14643603e-08]
 [  1.10324209e-07]
 [  9.18014637e-08]
 [  9.18898285e-

In [24]:
# The optimal value for x is stored in x.value.
print(x.value)
# The optimal Lagrange multiplier for a constraint
# is stored in constraint.dual_value.
print(constraints[0].dual_value)
print(constraints[1].dual_value)

[[  2.74656694e-08]
 [  2.85638784e-02]
 [  2.75730621e-08]
 [  4.78327626e-08]
 [  2.63777287e-09]
 [  1.49296787e-01]
 [  1.19199028e-07]
 [  2.09648396e-08]
 [  2.46747598e-01]
 [  5.78236593e-01]
 [  5.29023642e-09]
 [  1.01716277e-03]
 [  8.73750280e-09]
 [  2.26771054e-01]
 [  1.37218553e-08]
 [  2.10140304e-08]
 [  4.08413440e-08]
 [  4.52415813e-09]
 [  2.55078041e-08]
 [  6.32814150e-09]]
[[  2.50930786e+00]
 [  2.67848029e-06]
 [  2.78353157e+00]
 [  1.79423617e+00]
 [  1.30858969e+01]
 [  5.59976489e-07]
 [  7.37035767e-01]
 [  3.35348867e+00]
 [  3.53782570e-07]
 [  1.58362470e-07]
 [  8.93824713e+00]
 [  3.08624097e-04]
 [  7.02959474e+00]
 [  3.97069600e-07]
 [  4.71054026e+00]
 [  3.18864112e+00]
 [  2.06076796e+00]
 [  1.00817336e+01]
 [  3.04814645e+00]
 [  8.53266394e+00]]
[[  9.19428102e-08]
 [  9.59487136e-08]
 [  9.17209644e-08]
 [  9.18639022e-08]
 [  9.14643603e-08]
 [  1.10324209e-07]
 [  9.18014637e-08]
 [  9.18898285e-08]
 [  1.24868065e-07]
 [  2.22043136e-07