In [1]:
from scipy.misc import derivative
from functools import partial
import numpy as np

In [2]:
def derv(f, x):
    f_i = lambda i, val: f(np.vstack((x[:i], val, x[i+1:])))
    return np.hstack([derivative(partial(f_i, i), x[i], 1e-5)
                     for i in range(len(x))]).T

In [3]:
class AffineFunc(object):
    def __init__(self, A, b=0):
        self.A = A
        
    def __call__(self, x):
        return A * x
    
    def gradient(self, x=0):
        return A.T
    
class Square(object):
    def __call__(self, x):
        return x.T * x
    
    def gradient(self, x):
        return 2 * x

In [4]:
A = np.matrix([[1,2],[3,4]])
x = np.matrix([1.,1.]).reshape((2,1))

af = AffineFunc(A)
sq = Square()
quad = lambda x: sq(af(x))

print('numerically\n', derv(quad ,x))
print('numerically with prop\n', derv(af, x) * derv(sq ,af(x)))
print('prop\n', af.gradient(x) * sq.gradient(af(x)))

numerically
 [[ 48.]
 [ 68.]]
numerically with prop
 [[ 48.]
 [ 68.]]
prop
 [[ 48.]
 [ 68.]]
